import { saltBloodOfHadagan } from "./hadaganian/salt-blood.mjs"
import {
   boldIdea,
   citizensPerseverance,
   collectiveTactics,
   displayOfVirtue,
   hadaganianResourcefulness,
   helpingHand,
   nezebsPath,
   unconventionalWeaponry,
   voiceOfTheMotherland,
} from "./hadaganian/feats.mjs"
import {
   bloodFrenzy,
   competitiveSpirit,
   ferociousBeasts,
   fierceCompetitor,
   fierceCompetitorVictory,
   hunterDefense,
   infusedVesselAbsorbStrength,
   infusedVesselDeflectingSpirit,
   infusedVesselFleetSpirit,
   intimidatingEncouragement,
   majorVesselCloakOfPoison,
   naturesAnchor,
   orcTenacity,
   orcWays,
   overcomeShame,
   overcomeShamePenalty,
   prideInArms,
   rampagingTenacityRefund,
   rampagingTenacityStrike,
   retributorsEdge,
   righteousFury,
   snooze,
   spiritImbuingRitual,
   stubbornDefiance,
   victoriousVigor,
} from "./orc/feats.mjs"

export { saltBloodOfHadagan } from "./hadaganian/salt-blood.mjs"
export {
   boldIdea,
   citizensPerseverance,
   collectiveTactics,
   displayOfVirtue,
   hadaganianResourcefulness,
   helpingHand,
   nezebsPath,
   unconventionalWeaponry,
   voiceOfTheMotherland,
} from "./hadaganian/feats.mjs"
export {
   bloodFrenzy,
   competitiveSpirit,
   ferociousBeasts,
   fierceCompetitor,
   fierceCompetitorVictory,
   hunterDefense,
   infusedVesselAbsorbStrength,
   infusedVesselDeflectingSpirit,
   infusedVesselFleetSpirit,
   intimidatingEncouragement,
   majorVesselCloakOfPoison,
   naturesAnchor,
   orcTenacity,
   orcWays,
   overcomeShame,
   overcomeShamePenalty,
   prideInArms,
   rampagingTenacityRefund,
   rampagingTenacityStrike,
   retributorsEdge,
   righteousFury,
   snooze,
   spiritImbuingRitual,
   stubbornDefiance,
   victoriousVigor,
} from "./orc/feats.mjs"

export const ancestryActions = {
   hadaganian: {
      boldIdea,
      citizensPerseverance,
      collectiveTactics,
      displayOfVirtue,
      hadaganianResourcefulness,
      helpingHand,
      nezebsPath,
      saltBloodOfHadagan,
      unconventionalWeaponry,
      voiceOfTheMotherland,
   },
   orc: {
      bloodFrenzy,
      competitiveSpirit,
      ferociousBeasts,
      fierceCompetitor,
      fierceCompetitorVictory,
      hunterDefense,
      infusedVesselAbsorbStrength,
      infusedVesselDeflectingSpirit,
      infusedVesselFleetSpirit,
      intimidatingEncouragement,
      majorVesselCloakOfPoison,
      naturesAnchor,
      orcTenacity,
      orcWays,
      overcomeShame,
      overcomeShamePenalty,
      prideInArms,
      rampagingTenacityRefund,
      rampagingTenacityStrike,
      retributorsEdge,
      righteousFury,
      snooze,
      spiritImbuingRitual,
      stubbornDefiance,
      victoriousVigor,
   },
}
