name: Create Module Files For GitHub Release
env:
   project_url: "https://github.com/${{github.repository}}"
   latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/module.json"
   release_module_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip"
on:
   release:
      types: [published]
jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: write
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v6
         - name: Modify Module Manifest With Release-Specific Values
           run: |
              TAG="${{ github.event.release.tag_name }}"
              VERSION="${TAG#v}"
              jq --arg version "$VERSION" \
                 --arg url "${{ env.project_url }}" \
                 --arg manifest "${{ env.latest_manifest_url }}" \
                 --arg download "${{ env.release_module_url }}" \
                 '.version = $version | .url = $url | .manifest = $manifest | .download = $download' module.json > tmp.json && mv tmp.json module.json
         - name: Create Module Archive
           run: |
              zip --recurse-paths ./module.zip module.json templates scripts/ styles/ packs/ assets/ lang/
         - name: Update Release With Files
           uses: ncipollo/release-action@v1
           with:
              allowUpdates: true
              name: ${{ github.event.release.name }}
              draft: ${{ github.event.release.unpublished }}
              prerelease: ${{ github.event.release.prerelease }}
              token: ${{ secrets.GITHUB_TOKEN }}
              artifacts: "./module.json, ./module.zip"
              tag: ${{ github.event.release.tag_name }}
              body: ${{ github.event.release.body }}
